Add project YieldYak
token-terminal/smart-contract-registry pull request #10
Opened 2021-09-19 16:17 UTC by Jack-ZooFiLabs

Smart contracts of three github repo:
1. yieldyak/smart-contracts
2. yieldyak/governance-contracts
3. yieldyak/farm-contracts

2021-09-23 18:58 UTC, rbval requested changes
Few small changes and we're good to go:
1. Add `core` or `governance` to `type`
2. Add newline to the end

2021-09-23 18:58 UTC, rbval commented on projects/yield-yak.json
> +    "type": "type",
These should be should be either `core` or `governance`, for example:

`"type": "core"`

2021-09-23 18:58 UTC, rbval commented on projects/yield-yak.json
> +]
Nitpick: add a newline here.

2021-09-24 04:12 UTC, Jack-ZooFiLabs commented
Done. Please take a look.

2021-09-24 09:15 UTC, fnery commented
Thanks @Jack-ZooFiLabs. Ideally we'd appreciate the following fixes:
- fix versions that look like `vDAI`, `vETH`, `vLINK` (we expect something like `v1`, `v2`, etc...)
- could we have a bit more specific governance contract descriptions?
- checksummed contracts in explorer URLs -> lowercase contracts

2021-09-24 16:02 UTC, Jack-ZooFiLabs commented
Ok. Fixed a bug in the parser that gives "vDAI" etc. 

Re governance contract description, I'm not most familiar with it. I'll ask my teammate to send another pull request to update it. This is a bulk import done with a scanner. :)

Used lowercase contracts address.

2021-09-25 17:08 UTC, rbval approved these changes

2021-09-25 17:09 UTC, merged